media.source.webtools:
  type: media.source.field_aware
  label: 'Webtools media source configuration'
  mapping:
    widget_type:
      type: string
      label: 'Widget type'

oe_webtools_media.generic_widget_settings:
  type: config_object
  label: 'Webtools Media generic widget settings'
  mapping:
    blacklist:
      type: sequence
      label: 'Blacklist'
      sequence:
        type: string
        label: 'Webtools widget service'
