media.source.webtools:
  type: media.source.field_aware
  label: 'Webtools media source configuration'
  mapping:
    widget_type:
      type: string
      label: 'Widget type'
    generic_widget_type_blacklist:
      type: sequence
      label: 'Blacklist'
      sequence:
        type: string
        label: 'Webtools widget service'
