oe_webtools_captcha.settings:
  type: config_object
  label: 'Webtools Captcha settings'
  mapping:
    validationEndpoint:
      type: string
      label: 'Validation endpoint'
      description: 'The URL of the validation endpoint.'
