oe_webtools_laco_widget.settings:
  type: config_object
  label: 'Webtools Laco Widget settings'
  mapping:
    include_classes:
      type: sequence
      label: 'Include classes'
      sequence:
        type: string
        label: 'Class'
    exclude_classes:
      type: sequence
      label: 'Exclude classes'
      sequence:
        type: string
        label: 'Class'
    coverage:
      type: mapping
      label: 'Coverage'
      mapping:
        document:
          type: string
          label: 'Document'
        page:
          type: string
          label: 'Page'
    icon:
      type: string
      label: 'Icon'