oe_webtools_social_share.settings:
  type: config_object
  label: 'Webtools Social share settings'
  mapping:
    icons:
      type: boolean
      label: 'Icons'
      description: 'Whether the Social share block displays only icons without labels.'
