oe_webtools_cookie_consent.settings:
  type: config_object
  label: 'Webtools Cookie Consent settings'
  mapping:
    banner_popup:
      type: boolean
      label: 'CCK banner'
      description: 'Enable the banner.'
    media_oembed_popup:
      type: boolean
      label: 'CCK banner'
      description: 'Enable the override of media oembed iframe.'
